#Creating directory for a new problem in leetcode
directory_name= 2095-Delete_the_Middle_Node_of_a_Linked_List

build:
	cd leetcode && mkdir '$(directory_name)' && cd '$(directory_name)' && touch lab.c && code .