#Creating directory for a new problem in leetcode
directory_name= 2582-Pass_the_Pillow

build:
	cd .. && git add C/Makefile && cd C/leetcode && mkdir '$(directory_name)' && cd '$(directory_name)' && touch lab.c && code .